# -*- coding: utf-8 -*-
"""ImageClassification.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IpVBsX22v2I5Vh53J5WhkIAmqNvWQEs2
"""

#To install image downloader library in the system
!pip install bing-image-downloader

#To make a new directory where the images to be stored
!mkdir images

#Download few categories of images
from bing_image_downloader import downloader
downloader.download("pretty sunflower",limit=30,output_dir='images',adult_filter_off=True)

from bing_image_downloader import downloader
downloader.download("rugby leather ball",limit=30,output_dir='images',adult_filter_off=True)

from bing_image_downloader import downloader
downloader.download("icecream cone",limit=30,output_dir='images',adult_filter_off=True)

# Commented out IPython magic to ensure Python compatibility.
#To know the execution time
!pip install ipython-autotime
# %load_ext autotime

#Pre-processing
import os
import matplotlib.pyplot as plt
import numpy as np
from skimage.io import imread
from skimage.transform import resize

#Flatten the images
# 1.RESIZE
#2.FLATTENING
target= []
images= []
flat_data= []
DATADIR='/content/images'
CATAGORIES=['pretty_sunflower','rugby_leather_ball','icecream_cone']

for catagory in CATAGORIES :
  class_num = CATAGORIES.index(catagory)
  path = os.path.join(DATADIR,catagory)
  # Now we will read the values by iterating and is stored
  for img in os.listdir(path) :
    Image_Array = imread(os.path.join(path,img))
    # plt.imshow(Image_Array) to show the images
    Image_Resized = resize(Image_Array,(150,150,3))
    # Now passing the flattened verion
    flat_data.append(Image_Resized.flatten())
    images.append(Image_Resized)
    target.append(class_num)

_DATADIR='/content/images'
print(DATADIR)

